name: Build Geode Mod

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies & Geode CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential
          pip install geode-cli

      - name: Build Mod with CLI
        run: |
          geode package build
