name: Build Geode Mod

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        id: build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reumeow.frame_analyzer
          path: ${{ steps.build.outputs.build-output }}
